name: user
description: PartyOn User

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  image_card: ^0.0.4
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  proste_bezier_curve: ^2.0.2
  file_picker: ^10.1.9
  firebase_auth: ^5.5.4
  showcaseview: ^4.0.1
  cloud_firestore: ^5.6.8
  firebase_core:
  firebase_dynamic_links: ^6.0.8
  im_animations: ^0.1.2
  page_transition: ^2.2.1
  delayed_display: ^2.0.0
  firebase_analytics: ^11.4.6
  fluttertoast: ^8.2.12
  flutter_rating_bar: ^4.0.1
  flutter_slider_drawer: ^2.1.3
  random_string: ^2.3.1
  firebase_storage: ^12.4.6
  carousel_slider: ^5.0.0
  provider: ^6.1.5
  pin_code_fields: ^8.0.1
  flutter_easyloading: ^3.0.5
  email_validator: ^3.0.0
#  google_sign_in: ^6.3.0
  geolocator: ^11.0.0
  geocoding: ^4.0.0
  hive_flutter: ^1.1.0
  image_cropper: ^9.1.0
  flutter_native_splash: any
#  wakelock: any
  permission_handler: 
  share_plus:
  music_visualizer: ^1.0.4
  auto_size_text: ^3.0.0
  razorpay_flutter: ^1.4.0
  dart_ipify: ^1.1.1
  crypto: ^3.0.6
  photo_view: ^0.14.0
  cloudflare: ^3.1.0+16
  pretty_qr_code: ^3.4.0
  url_launcher: ^6.3.1
  intl: ^0.19.0
  video_player: ^2.9.5
  chewie: ^1.11.3
  firebase_database: ^11.3.6
  http: ^1.0.0
  hive: ^2.2.3
  shimmer: ^3.0.0
  package_info_plus: any
  flutter_phosphor_icons: ^0.0.1+6
  readmore: ^3.0.0
  in_app_update: ^4.2.3
  upgrader: any
  bottom_picker: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1


dependency_overrides:
  firebase_auth_web:
  firebase_storage_web:
  image_cropper_for_web:
  image_cropper_platform_interface: ^6.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#f70042"


flutter_native_splash:
  image: assets/splash.png
  color: "#000000"

  android_12:
    image: assets/splash.png
    color: "#000000"
    android_gravity: fill-horizontal

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/gold_logo.png
    - assets/
    - assets/welcome/
    - assets/category/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
