// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
    // throw UnsupportedError(
    //   'DefaultFirebaseOptions have not been configured for android - '
    //   'you can reconfigure this by running the FlutterFire CLI again.',
    // );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdJcZdueFYJLEs26fqSLhjn14ns9CvV1Y',
    appId: '1:774845460870:ios:d836926a2ff0600c56bc07',
    messagingSenderId: '774845460870',
    projectId: 'partyon-artist',
    databaseURL: 'https://partyon-artist-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'partyon-artist.appspot.com',
    androidClientId: '774845460870-2kl7nj2rl2oa32kesp7a0vtrvigeuaka.apps.googleusercontent.com',
    iosClientId: '774845460870-u6cj0qa03sd3k6vraonmmac3j24murb3.apps.googleusercontent.com',
    iosBundleId: 'hashtag.partyon.user',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABTFYsW2tcUjieHi3Lu4dUGr8ANXnmea4',
    appId: '1:774845460870:android:a3bbb5e0acd8088b56bc07',
    messagingSenderId: '774845460870',
    projectId: 'partyon-artist',
    databaseURL: 'https://partyon-artist-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'partyon-artist.appspot.com',
    androidClientId: '774845460870-2ibod8tf4l0bkallm78co6ohqis9i77l.apps.googleusercontent.com',
    iosClientId: '774845460870-2ibod8tf4l0bkallm78co6ohqis9i77l.apps.googleusercontent.com',
    iosBundleId: 'hashtag.partyon.partner',
  );

  static const FirebaseOptions web = FirebaseOptions(
    // apiKey: "AIzaSyCRNAx5nOIj8Z9AKfm_Pn7lxje1kRSk4OA",
    // authDomain: "partyon-user.firebaseapp.com",
    // projectId: "partyon-user",
    // storageBucket: "partyon-user.firebasestorage.app",
    // messagingSenderId: "593508339629",
    // appId: "1:593508339629:web:90c02b29062911bb165b24",
    // measurementId: "G-BX6F4GP78L"
      apiKey: "AIzaSyC8rMzrvvz0ZgEqnv6d88tUOTEKktgST_c",
      authDomain: "partyon-artist.firebaseapp.com",
      databaseURL: "https://partyon-artist-default-rtdb.asia-southeast1.firebasedatabase.app",
      projectId: "partyon-artist",
      storageBucket: "partyon-artist.appspot.com",
      messagingSenderId: "774845460870",
      appId: "1:774845460870:web:651a7ea4a314b89956bc07",
      measurementId: "G-043F41BTBS"
  );
}
